/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as StatusSlugRouteImport } from './routes/status/$slug'
import { Route as AdminSettingsRouteRouteImport } from './routes/_admin/settings/route'
import { Route as AdminNotificationsRouteRouteImport } from './routes/_admin/notifications/route'
import { Route as AdminIncidentsRouteRouteImport } from './routes/_admin/incidents/route'
import { Route as AdminIndexRouteRouteImport } from './routes/_admin/index/route'
import { Route as AdminStatusPagesIndexRouteImport } from './routes/_admin/status-pages/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/_admin/settings/index'
import { Route as AdminMonitorsIndexRouteImport } from './routes/_admin/monitors/index'
import { Route as AdminStatusPagesNewRouteImport } from './routes/_admin/status-pages/new'
import { Route as AdminSettingsSectionRouteImport } from './routes/_admin/settings/$section'
import { Route as AdminMonitorsNewRouteImport } from './routes/_admin/monitors/new'
import { Route as AdminMonitorsMonitorIdRouteRouteImport } from './routes/_admin/monitors/$monitorId/route'
import { Route as AdminMonitorsMonitorIdIndexRouteImport } from './routes/_admin/monitors/$monitorId/index'
import { Route as AdminStatusPagesPageIdEditRouteImport } from './routes/_admin/status-pages/$pageId/edit'
import { Route as AdminMonitorsMonitorIdSettingsRouteImport } from './routes/_admin/monitors/$monitorId/settings'
import { Route as AdminMonitorsMonitorIdLogsRouteImport } from './routes/_admin/monitors/$monitorId/logs'
import { Route as AdminMonitorsMonitorIdIncidentsRouteImport } from './routes/_admin/monitors/$monitorId/incidents'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRouteRoute = AdminNotificationsRouteRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIncidentsRouteRoute = AdminIncidentsRouteRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIndexRouteRoute = AdminIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStatusPagesIndexRoute = AdminStatusPagesIndexRouteImport.update({
  id: '/status-pages/',
  path: '/status-pages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminMonitorsIndexRoute = AdminMonitorsIndexRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStatusPagesNewRoute = AdminStatusPagesNewRouteImport.update({
  id: '/status-pages/new',
  path: '/status-pages/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsSectionRoute = AdminSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminMonitorsNewRoute = AdminMonitorsNewRouteImport.update({
  id: '/monitors/new',
  path: '/monitors/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitorsMonitorIdRouteRoute =
  AdminMonitorsMonitorIdRouteRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminMonitorsMonitorIdIndexRoute =
  AdminMonitorsMonitorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMonitorsMonitorIdRouteRoute,
  } as any)
const AdminStatusPagesPageIdEditRoute =
  AdminStatusPagesPageIdEditRouteImport.update({
    id: '/status-pages/$pageId/edit',
    path: '/status-pages/$pageId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminMonitorsMonitorIdSettingsRoute =
  AdminMonitorsMonitorIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminMonitorsMonitorIdRouteRoute,
  } as any)
const AdminMonitorsMonitorIdLogsRoute =
  AdminMonitorsMonitorIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AdminMonitorsMonitorIdRouteRoute,
  } as any)
const AdminMonitorsMonitorIdIncidentsRoute =
  AdminMonitorsMonitorIdIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AdminMonitorsMonitorIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRouteRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/incidents': typeof AdminIncidentsRouteRoute
  '/notifications': typeof AdminNotificationsRouteRoute
  '/settings': typeof AdminSettingsRouteRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/monitors/$monitorId': typeof AdminMonitorsMonitorIdRouteRouteWithChildren
  '/monitors/new': typeof AdminMonitorsNewRoute
  '/settings/$section': typeof AdminSettingsSectionRoute
  '/status-pages/new': typeof AdminStatusPagesNewRoute
  '/monitors/': typeof AdminMonitorsIndexRoute
  '/settings/': typeof AdminSettingsIndexRoute
  '/status-pages/': typeof AdminStatusPagesIndexRoute
  '/monitors/$monitorId/incidents': typeof AdminMonitorsMonitorIdIncidentsRoute
  '/monitors/$monitorId/logs': typeof AdminMonitorsMonitorIdLogsRoute
  '/monitors/$monitorId/settings': typeof AdminMonitorsMonitorIdSettingsRoute
  '/status-pages/$pageId/edit': typeof AdminStatusPagesPageIdEditRoute
  '/monitors/$monitorId/': typeof AdminMonitorsMonitorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRouteRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/incidents': typeof AdminIncidentsRouteRoute
  '/notifications': typeof AdminNotificationsRouteRoute
  '/status/$slug': typeof StatusSlugRoute
  '/monitors/new': typeof AdminMonitorsNewRoute
  '/settings/$section': typeof AdminSettingsSectionRoute
  '/status-pages/new': typeof AdminStatusPagesNewRoute
  '/monitors': typeof AdminMonitorsIndexRoute
  '/settings': typeof AdminSettingsIndexRoute
  '/status-pages': typeof AdminStatusPagesIndexRoute
  '/monitors/$monitorId/incidents': typeof AdminMonitorsMonitorIdIncidentsRoute
  '/monitors/$monitorId/logs': typeof AdminMonitorsMonitorIdLogsRoute
  '/monitors/$monitorId/settings': typeof AdminMonitorsMonitorIdSettingsRoute
  '/status-pages/$pageId/edit': typeof AdminStatusPagesPageIdEditRoute
  '/monitors/$monitorId': typeof AdminMonitorsMonitorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_admin/': typeof AdminIndexRouteRoute
  '/_admin/incidents': typeof AdminIncidentsRouteRoute
  '/_admin/notifications': typeof AdminNotificationsRouteRoute
  '/_admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/_admin/monitors/$monitorId': typeof AdminMonitorsMonitorIdRouteRouteWithChildren
  '/_admin/monitors/new': typeof AdminMonitorsNewRoute
  '/_admin/settings/$section': typeof AdminSettingsSectionRoute
  '/_admin/status-pages/new': typeof AdminStatusPagesNewRoute
  '/_admin/monitors/': typeof AdminMonitorsIndexRoute
  '/_admin/settings/': typeof AdminSettingsIndexRoute
  '/_admin/status-pages/': typeof AdminStatusPagesIndexRoute
  '/_admin/monitors/$monitorId/incidents': typeof AdminMonitorsMonitorIdIncidentsRoute
  '/_admin/monitors/$monitorId/logs': typeof AdminMonitorsMonitorIdLogsRoute
  '/_admin/monitors/$monitorId/settings': typeof AdminMonitorsMonitorIdSettingsRoute
  '/_admin/status-pages/$pageId/edit': typeof AdminStatusPagesPageIdEditRoute
  '/_admin/monitors/$monitorId/': typeof AdminMonitorsMonitorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/incidents'
    | '/notifications'
    | '/settings'
    | '/status/$slug'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/settings/$section'
    | '/status-pages/new'
    | '/monitors/'
    | '/settings/'
    | '/status-pages/'
    | '/monitors/$monitorId/incidents'
    | '/monitors/$monitorId/logs'
    | '/monitors/$monitorId/settings'
    | '/status-pages/$pageId/edit'
    | '/monitors/$monitorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/incidents'
    | '/notifications'
    | '/status/$slug'
    | '/monitors/new'
    | '/settings/$section'
    | '/status-pages/new'
    | '/monitors'
    | '/settings'
    | '/status-pages'
    | '/monitors/$monitorId/incidents'
    | '/monitors/$monitorId/logs'
    | '/monitors/$monitorId/settings'
    | '/status-pages/$pageId/edit'
    | '/monitors/$monitorId'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/setup'
    | '/_admin/'
    | '/_admin/incidents'
    | '/_admin/notifications'
    | '/_admin/settings'
    | '/status/$slug'
    | '/_admin/monitors/$monitorId'
    | '/_admin/monitors/new'
    | '/_admin/settings/$section'
    | '/_admin/status-pages/new'
    | '/_admin/monitors/'
    | '/_admin/settings/'
    | '/_admin/status-pages/'
    | '/_admin/monitors/$monitorId/incidents'
    | '/_admin/monitors/$monitorId/logs'
    | '/_admin/monitors/$monitorId/settings'
    | '/_admin/status-pages/$pageId/edit'
    | '/_admin/monitors/$monitorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  StatusSlugRoute: typeof StatusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/incidents': {
      id: '/_admin/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/': {
      id: '/_admin/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/status-pages/': {
      id: '/_admin/status-pages/'
      path: '/status-pages'
      fullPath: '/status-pages/'
      preLoaderRoute: typeof AdminStatusPagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings/': {
      id: '/_admin/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/monitors/': {
      id: '/_admin/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof AdminMonitorsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/status-pages/new': {
      id: '/_admin/status-pages/new'
      path: '/status-pages/new'
      fullPath: '/status-pages/new'
      preLoaderRoute: typeof AdminStatusPagesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings/$section': {
      id: '/_admin/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AdminSettingsSectionRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/monitors/new': {
      id: '/_admin/monitors/new'
      path: '/monitors/new'
      fullPath: '/monitors/new'
      preLoaderRoute: typeof AdminMonitorsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/monitors/$monitorId': {
      id: '/_admin/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof AdminMonitorsMonitorIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/monitors/$monitorId/': {
      id: '/_admin/monitors/$monitorId/'
      path: '/'
      fullPath: '/monitors/$monitorId/'
      preLoaderRoute: typeof AdminMonitorsMonitorIdIndexRouteImport
      parentRoute: typeof AdminMonitorsMonitorIdRouteRoute
    }
    '/_admin/status-pages/$pageId/edit': {
      id: '/_admin/status-pages/$pageId/edit'
      path: '/status-pages/$pageId/edit'
      fullPath: '/status-pages/$pageId/edit'
      preLoaderRoute: typeof AdminStatusPagesPageIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/monitors/$monitorId/settings': {
      id: '/_admin/monitors/$monitorId/settings'
      path: '/settings'
      fullPath: '/monitors/$monitorId/settings'
      preLoaderRoute: typeof AdminMonitorsMonitorIdSettingsRouteImport
      parentRoute: typeof AdminMonitorsMonitorIdRouteRoute
    }
    '/_admin/monitors/$monitorId/logs': {
      id: '/_admin/monitors/$monitorId/logs'
      path: '/logs'
      fullPath: '/monitors/$monitorId/logs'
      preLoaderRoute: typeof AdminMonitorsMonitorIdLogsRouteImport
      parentRoute: typeof AdminMonitorsMonitorIdRouteRoute
    }
    '/_admin/monitors/$monitorId/incidents': {
      id: '/_admin/monitors/$monitorId/incidents'
      path: '/incidents'
      fullPath: '/monitors/$monitorId/incidents'
      preLoaderRoute: typeof AdminMonitorsMonitorIdIncidentsRouteImport
      parentRoute: typeof AdminMonitorsMonitorIdRouteRoute
    }
  }
}

interface AdminSettingsRouteRouteChildren {
  AdminSettingsSectionRoute: typeof AdminSettingsSectionRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsSectionRoute: AdminSettingsSectionRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminMonitorsMonitorIdRouteRouteChildren {
  AdminMonitorsMonitorIdIncidentsRoute: typeof AdminMonitorsMonitorIdIncidentsRoute
  AdminMonitorsMonitorIdLogsRoute: typeof AdminMonitorsMonitorIdLogsRoute
  AdminMonitorsMonitorIdSettingsRoute: typeof AdminMonitorsMonitorIdSettingsRoute
  AdminMonitorsMonitorIdIndexRoute: typeof AdminMonitorsMonitorIdIndexRoute
}

const AdminMonitorsMonitorIdRouteRouteChildren: AdminMonitorsMonitorIdRouteRouteChildren =
  {
    AdminMonitorsMonitorIdIncidentsRoute: AdminMonitorsMonitorIdIncidentsRoute,
    AdminMonitorsMonitorIdLogsRoute: AdminMonitorsMonitorIdLogsRoute,
    AdminMonitorsMonitorIdSettingsRoute: AdminMonitorsMonitorIdSettingsRoute,
    AdminMonitorsMonitorIdIndexRoute: AdminMonitorsMonitorIdIndexRoute,
  }

const AdminMonitorsMonitorIdRouteRouteWithChildren =
  AdminMonitorsMonitorIdRouteRoute._addFileChildren(
    AdminMonitorsMonitorIdRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminIndexRouteRoute: typeof AdminIndexRouteRoute
  AdminIncidentsRouteRoute: typeof AdminIncidentsRouteRoute
  AdminNotificationsRouteRoute: typeof AdminNotificationsRouteRoute
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminMonitorsMonitorIdRouteRoute: typeof AdminMonitorsMonitorIdRouteRouteWithChildren
  AdminMonitorsNewRoute: typeof AdminMonitorsNewRoute
  AdminStatusPagesNewRoute: typeof AdminStatusPagesNewRoute
  AdminMonitorsIndexRoute: typeof AdminMonitorsIndexRoute
  AdminStatusPagesIndexRoute: typeof AdminStatusPagesIndexRoute
  AdminStatusPagesPageIdEditRoute: typeof AdminStatusPagesPageIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRouteRoute: AdminIndexRouteRoute,
  AdminIncidentsRouteRoute: AdminIncidentsRouteRoute,
  AdminNotificationsRouteRoute: AdminNotificationsRouteRoute,
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminMonitorsMonitorIdRouteRoute:
    AdminMonitorsMonitorIdRouteRouteWithChildren,
  AdminMonitorsNewRoute: AdminMonitorsNewRoute,
  AdminStatusPagesNewRoute: AdminStatusPagesNewRoute,
  AdminMonitorsIndexRoute: AdminMonitorsIndexRoute,
  AdminStatusPagesIndexRoute: AdminStatusPagesIndexRoute,
  AdminStatusPagesPageIdEditRoute: AdminStatusPagesPageIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  StatusSlugRoute: StatusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
