/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as StatusSlugRouteImport } from './routes/status/$slug'
import { Route as AdminStatusPagesRouteRouteImport } from './routes/_admin/status-pages/route'
import { Route as AdminSettingsRouteRouteImport } from './routes/_admin/settings/route'
import { Route as AdminNotificationsRouteRouteImport } from './routes/_admin/notifications/route'
import { Route as AdminMonitorsRouteRouteImport } from './routes/_admin/monitors/route'
import { Route as AdminIncidentsRouteRouteImport } from './routes/_admin/incidents/route'
import { Route as AdminIndexRouteRouteImport } from './routes/_admin/index/route'
import { Route as AdminStatusPagesNewRouteImport } from './routes/_admin/status-pages/new'
import { Route as AdminSettingsSectionRouteImport } from './routes/_admin/settings/$section'
import { Route as AdminMonitorsNewRouteImport } from './routes/_admin/monitors/new'
import { Route as AdminMonitorsMonitorIdRouteRouteImport } from './routes/_admin/monitors/$monitorId/route'
import { Route as AdminStatusPagesPageIdEditRouteImport } from './routes/_admin/status-pages/$pageId/edit'
import { Route as AdminMonitorsMonitorIdSettingsRouteImport } from './routes/_admin/monitors/$monitorId/settings'
import { Route as AdminMonitorsMonitorIdLogsRouteImport } from './routes/_admin/monitors/$monitorId/logs'
import { Route as AdminMonitorsMonitorIdIncidentsRouteImport } from './routes/_admin/monitors/$monitorId/incidents'
import { Route as AdminMonitorsMonitorIdEditRouteImport } from './routes/_admin/monitors/$monitorId/edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatusPagesRouteRoute = AdminStatusPagesRouteRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRouteRoute = AdminNotificationsRouteRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitorsRouteRoute = AdminMonitorsRouteRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIncidentsRouteRoute = AdminIncidentsRouteRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIndexRouteRoute = AdminIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStatusPagesNewRoute = AdminStatusPagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminStatusPagesRouteRoute,
} as any)
const AdminSettingsSectionRoute = AdminSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminMonitorsNewRoute = AdminMonitorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMonitorsRouteRoute,
} as any)
const AdminMonitorsMonitorIdRouteRoute =
  AdminMonitorsMonitorIdRouteRouteImport.update({
    id: '/$monitorId',
    path: '/$monitorId',
    getParentRoute: () => AdminMonitorsRouteRoute,
  } as any)
const AdminStatusPagesPageIdEditRoute =
  AdminStatusPagesPageIdEditRouteImport.update({
    id: '/$pageId/edit',
    path: '/$pageId/edit',
    getParentRoute: () => AdminStatusPagesRouteRoute,
  } as any)
const AdminMonitorsMonitorIdSettingsRoute =
  AdminMonitorsMonitorIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminMonitorsMonitorIdRouteRoute,
  } as any)
const AdminMonitorsMonitorIdLogsRoute =
  AdminMonitorsMonitorIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AdminMonitorsMonitorIdRouteRoute,
  } as any)
const AdminMonitorsMonitorIdIncidentsRoute =
  AdminMonitorsMonitorIdIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AdminMonitorsMonitorIdRouteRoute,
  } as any)
const AdminMonitorsMonitorIdEditRoute =
  AdminMonitorsMonitorIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminMonitorsMonitorIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRouteRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/incidents': typeof AdminIncidentsRouteRoute
  '/monitors': typeof AdminMonitorsRouteRouteWithChildren
  '/notifications': typeof AdminNotificationsRouteRoute
  '/settings': typeof AdminSettingsRouteRouteWithChildren
  '/status-pages': typeof AdminStatusPagesRouteRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/monitors/$monitorId': typeof AdminMonitorsMonitorIdRouteRouteWithChildren
  '/monitors/new': typeof AdminMonitorsNewRoute
  '/settings/$section': typeof AdminSettingsSectionRoute
  '/status-pages/new': typeof AdminStatusPagesNewRoute
  '/monitors/$monitorId/edit': typeof AdminMonitorsMonitorIdEditRoute
  '/monitors/$monitorId/incidents': typeof AdminMonitorsMonitorIdIncidentsRoute
  '/monitors/$monitorId/logs': typeof AdminMonitorsMonitorIdLogsRoute
  '/monitors/$monitorId/settings': typeof AdminMonitorsMonitorIdSettingsRoute
  '/status-pages/$pageId/edit': typeof AdminStatusPagesPageIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRouteRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/incidents': typeof AdminIncidentsRouteRoute
  '/monitors': typeof AdminMonitorsRouteRouteWithChildren
  '/notifications': typeof AdminNotificationsRouteRoute
  '/settings': typeof AdminSettingsRouteRouteWithChildren
  '/status-pages': typeof AdminStatusPagesRouteRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/monitors/$monitorId': typeof AdminMonitorsMonitorIdRouteRouteWithChildren
  '/monitors/new': typeof AdminMonitorsNewRoute
  '/settings/$section': typeof AdminSettingsSectionRoute
  '/status-pages/new': typeof AdminStatusPagesNewRoute
  '/monitors/$monitorId/edit': typeof AdminMonitorsMonitorIdEditRoute
  '/monitors/$monitorId/incidents': typeof AdminMonitorsMonitorIdIncidentsRoute
  '/monitors/$monitorId/logs': typeof AdminMonitorsMonitorIdLogsRoute
  '/monitors/$monitorId/settings': typeof AdminMonitorsMonitorIdSettingsRoute
  '/status-pages/$pageId/edit': typeof AdminStatusPagesPageIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_admin/': typeof AdminIndexRouteRoute
  '/_admin/incidents': typeof AdminIncidentsRouteRoute
  '/_admin/monitors': typeof AdminMonitorsRouteRouteWithChildren
  '/_admin/notifications': typeof AdminNotificationsRouteRoute
  '/_admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/_admin/status-pages': typeof AdminStatusPagesRouteRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/_admin/monitors/$monitorId': typeof AdminMonitorsMonitorIdRouteRouteWithChildren
  '/_admin/monitors/new': typeof AdminMonitorsNewRoute
  '/_admin/settings/$section': typeof AdminSettingsSectionRoute
  '/_admin/status-pages/new': typeof AdminStatusPagesNewRoute
  '/_admin/monitors/$monitorId/edit': typeof AdminMonitorsMonitorIdEditRoute
  '/_admin/monitors/$monitorId/incidents': typeof AdminMonitorsMonitorIdIncidentsRoute
  '/_admin/monitors/$monitorId/logs': typeof AdminMonitorsMonitorIdLogsRoute
  '/_admin/monitors/$monitorId/settings': typeof AdminMonitorsMonitorIdSettingsRoute
  '/_admin/status-pages/$pageId/edit': typeof AdminStatusPagesPageIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/incidents'
    | '/monitors'
    | '/notifications'
    | '/settings'
    | '/status-pages'
    | '/status/$slug'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/settings/$section'
    | '/status-pages/new'
    | '/monitors/$monitorId/edit'
    | '/monitors/$monitorId/incidents'
    | '/monitors/$monitorId/logs'
    | '/monitors/$monitorId/settings'
    | '/status-pages/$pageId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/incidents'
    | '/monitors'
    | '/notifications'
    | '/settings'
    | '/status-pages'
    | '/status/$slug'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/settings/$section'
    | '/status-pages/new'
    | '/monitors/$monitorId/edit'
    | '/monitors/$monitorId/incidents'
    | '/monitors/$monitorId/logs'
    | '/monitors/$monitorId/settings'
    | '/status-pages/$pageId/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/setup'
    | '/_admin/'
    | '/_admin/incidents'
    | '/_admin/monitors'
    | '/_admin/notifications'
    | '/_admin/settings'
    | '/_admin/status-pages'
    | '/status/$slug'
    | '/_admin/monitors/$monitorId'
    | '/_admin/monitors/new'
    | '/_admin/settings/$section'
    | '/_admin/status-pages/new'
    | '/_admin/monitors/$monitorId/edit'
    | '/_admin/monitors/$monitorId/incidents'
    | '/_admin/monitors/$monitorId/logs'
    | '/_admin/monitors/$monitorId/settings'
    | '/_admin/status-pages/$pageId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  StatusSlugRoute: typeof StatusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/status-pages': {
      id: '/_admin/status-pages'
      path: '/status-pages'
      fullPath: '/status-pages'
      preLoaderRoute: typeof AdminStatusPagesRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/monitors': {
      id: '/_admin/monitors'
      path: '/monitors'
      fullPath: '/monitors'
      preLoaderRoute: typeof AdminMonitorsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/incidents': {
      id: '/_admin/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/': {
      id: '/_admin/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/status-pages/new': {
      id: '/_admin/status-pages/new'
      path: '/new'
      fullPath: '/status-pages/new'
      preLoaderRoute: typeof AdminStatusPagesNewRouteImport
      parentRoute: typeof AdminStatusPagesRouteRoute
    }
    '/_admin/settings/$section': {
      id: '/_admin/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AdminSettingsSectionRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/monitors/new': {
      id: '/_admin/monitors/new'
      path: '/new'
      fullPath: '/monitors/new'
      preLoaderRoute: typeof AdminMonitorsNewRouteImport
      parentRoute: typeof AdminMonitorsRouteRoute
    }
    '/_admin/monitors/$monitorId': {
      id: '/_admin/monitors/$monitorId'
      path: '/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof AdminMonitorsMonitorIdRouteRouteImport
      parentRoute: typeof AdminMonitorsRouteRoute
    }
    '/_admin/status-pages/$pageId/edit': {
      id: '/_admin/status-pages/$pageId/edit'
      path: '/$pageId/edit'
      fullPath: '/status-pages/$pageId/edit'
      preLoaderRoute: typeof AdminStatusPagesPageIdEditRouteImport
      parentRoute: typeof AdminStatusPagesRouteRoute
    }
    '/_admin/monitors/$monitorId/settings': {
      id: '/_admin/monitors/$monitorId/settings'
      path: '/settings'
      fullPath: '/monitors/$monitorId/settings'
      preLoaderRoute: typeof AdminMonitorsMonitorIdSettingsRouteImport
      parentRoute: typeof AdminMonitorsMonitorIdRouteRoute
    }
    '/_admin/monitors/$monitorId/logs': {
      id: '/_admin/monitors/$monitorId/logs'
      path: '/logs'
      fullPath: '/monitors/$monitorId/logs'
      preLoaderRoute: typeof AdminMonitorsMonitorIdLogsRouteImport
      parentRoute: typeof AdminMonitorsMonitorIdRouteRoute
    }
    '/_admin/monitors/$monitorId/incidents': {
      id: '/_admin/monitors/$monitorId/incidents'
      path: '/incidents'
      fullPath: '/monitors/$monitorId/incidents'
      preLoaderRoute: typeof AdminMonitorsMonitorIdIncidentsRouteImport
      parentRoute: typeof AdminMonitorsMonitorIdRouteRoute
    }
    '/_admin/monitors/$monitorId/edit': {
      id: '/_admin/monitors/$monitorId/edit'
      path: '/edit'
      fullPath: '/monitors/$monitorId/edit'
      preLoaderRoute: typeof AdminMonitorsMonitorIdEditRouteImport
      parentRoute: typeof AdminMonitorsMonitorIdRouteRoute
    }
  }
}

interface AdminMonitorsMonitorIdRouteRouteChildren {
  AdminMonitorsMonitorIdEditRoute: typeof AdminMonitorsMonitorIdEditRoute
  AdminMonitorsMonitorIdIncidentsRoute: typeof AdminMonitorsMonitorIdIncidentsRoute
  AdminMonitorsMonitorIdLogsRoute: typeof AdminMonitorsMonitorIdLogsRoute
  AdminMonitorsMonitorIdSettingsRoute: typeof AdminMonitorsMonitorIdSettingsRoute
}

const AdminMonitorsMonitorIdRouteRouteChildren: AdminMonitorsMonitorIdRouteRouteChildren =
  {
    AdminMonitorsMonitorIdEditRoute: AdminMonitorsMonitorIdEditRoute,
    AdminMonitorsMonitorIdIncidentsRoute: AdminMonitorsMonitorIdIncidentsRoute,
    AdminMonitorsMonitorIdLogsRoute: AdminMonitorsMonitorIdLogsRoute,
    AdminMonitorsMonitorIdSettingsRoute: AdminMonitorsMonitorIdSettingsRoute,
  }

const AdminMonitorsMonitorIdRouteRouteWithChildren =
  AdminMonitorsMonitorIdRouteRoute._addFileChildren(
    AdminMonitorsMonitorIdRouteRouteChildren,
  )

interface AdminMonitorsRouteRouteChildren {
  AdminMonitorsMonitorIdRouteRoute: typeof AdminMonitorsMonitorIdRouteRouteWithChildren
  AdminMonitorsNewRoute: typeof AdminMonitorsNewRoute
}

const AdminMonitorsRouteRouteChildren: AdminMonitorsRouteRouteChildren = {
  AdminMonitorsMonitorIdRouteRoute:
    AdminMonitorsMonitorIdRouteRouteWithChildren,
  AdminMonitorsNewRoute: AdminMonitorsNewRoute,
}

const AdminMonitorsRouteRouteWithChildren =
  AdminMonitorsRouteRoute._addFileChildren(AdminMonitorsRouteRouteChildren)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsSectionRoute: typeof AdminSettingsSectionRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsSectionRoute: AdminSettingsSectionRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminStatusPagesRouteRouteChildren {
  AdminStatusPagesNewRoute: typeof AdminStatusPagesNewRoute
  AdminStatusPagesPageIdEditRoute: typeof AdminStatusPagesPageIdEditRoute
}

const AdminStatusPagesRouteRouteChildren: AdminStatusPagesRouteRouteChildren = {
  AdminStatusPagesNewRoute: AdminStatusPagesNewRoute,
  AdminStatusPagesPageIdEditRoute: AdminStatusPagesPageIdEditRoute,
}

const AdminStatusPagesRouteRouteWithChildren =
  AdminStatusPagesRouteRoute._addFileChildren(
    AdminStatusPagesRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminIndexRouteRoute: typeof AdminIndexRouteRoute
  AdminIncidentsRouteRoute: typeof AdminIncidentsRouteRoute
  AdminMonitorsRouteRoute: typeof AdminMonitorsRouteRouteWithChildren
  AdminNotificationsRouteRoute: typeof AdminNotificationsRouteRoute
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminStatusPagesRouteRoute: typeof AdminStatusPagesRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRouteRoute: AdminIndexRouteRoute,
  AdminIncidentsRouteRoute: AdminIncidentsRouteRoute,
  AdminMonitorsRouteRoute: AdminMonitorsRouteRouteWithChildren,
  AdminNotificationsRouteRoute: AdminNotificationsRouteRoute,
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminStatusPagesRouteRoute: AdminStatusPagesRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  StatusSlugRoute: StatusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
